import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from 'geist/font/mono'

export const metadata: Metadata = {
  title: "OpenLLM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} bg-dark-gray text-white sm:text-base text-sm font-sans`}>
        {children}
      </body>
    </html>
  );
}